# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# test.py
# Created on: 2017-09-14 15:58:09.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

arcpy.env.workspace = r"C:\Users\student\Documents\ArcGIS\Default.gdb"

# Local variables:
input = arcpy.PointGeometry(arcpy.Point(123,123))
Buffer10000 = "in_memory\\Buffer10000"
result = "Buffer10000_Buffer"

# Process: 버퍼(Buffer)
arcpy.Buffer_analysis(input, Buffer10000, "100 Meters", "FULL", "ROUND", "NONE", "", "PLANAR")

# Process: 버퍼(Buffer) (2)
arcpy.Buffer_analysis(Buffer10000, result, "100 Meters", "FULL", "ROUND", "NONE", "", "PLANAR")


# ---------------------------------------------------------------------------
#Use arcpy.da SearchCursor to access the in_memory
import arcpy
pnt = arcpy.Point(6282633.845, 1838254.582)

#Create geometry object from in_memory
geom = arcpy.Geometry("Point", pnt)

#Buffer the point and use in_memory
#feature class for output
bufferPnt = arcpy.Buffer_analysis(geom, "in_memory/bufferPnt", "5280 feet")

#Clip meters based on in_memory buffer output
clipMeters = arcpy.Clip_analysis("ParkingMeters", bufferPnt, "in_memory/clipMeters")#(workspace>featureName, Crip feature, output)

#Access in_memory\clipMeters features using
#an arcpy.da SearchCursor and report the meter ID and meter type
with arcpy.da.SearchCursor("in_memory/clipMeters", ["MeterID", "TYPE"]) as cursor:
    for row in cursor:
        print "ID: {0}, Type: {1}".format(row[0], row[1])







